version: "3.7"

services:
  mysql-8:
    image: mysql:8.0.30
    container_name: mysql-8-wordpress
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
    command: "--default-authentication-plugin=mysql_native_password"
  wordpress:
    depends_on: 
      - mysql-8
    hostname: wordpress
    image: wordpress
    container_name: wordpress-mysql-8
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
  dbdata:
      
